version: '3.1'

services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 80:80
      volumes:
        - ./src:/var/www/html/

    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    composer:
      restart: 'no'
      image: library/composer:latest
      command: install
      volumes:
        - ./src:/var/www/html/












